RANDOM_SEED: 0

DATA:
  VOCABULARY: data/vocabulary
  TRAIN_FEATURES: temp/small_sample_test_1.h5
  INFER_FEATURES: temp/small_sample_test_1.h5

  TRAIN_CAPTIONS: temp/coco_sample_1_caption.json
  INFER_CAPTIONS: temp/coco_sample_1_caption.json

  MAX_CAPTION_LENGTH:  20

MODEL:
  IMAGE_FEATURE_SIZE: 2048
  EMBEDDING_SIZE: 300
  NUM_ATTENTION_BLOCK: 4
  CAPTION_LENGTH: 20
  VOCAB_SIZE: 9343
  HIDDEN_SIZE: 400
  FEED_FORWARD_DIM: 128
  ENCODE_DIM: 2048
  NUM_HEADS: 2
  # NUM_LAYERS: 1
  USE_CBS: False
  BEAM_SIZE: 5
  ATTENTION_PROJECTION_SIZE: 768
   
  

OPTIM:
  BATCH_SIZE: 10
  NUM_ITERATIONS: 800
  LR: 0.015
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.001
  CLIP_GRADIENTS: 12.5